import { useI18n } from '../i18n'
import type { LanInfo } from '../lan'

type Props = {
  info: LanInfo | null
  devices: number
  busy: boolean
  error: string | null
  native: boolean
  onStart: () => void
  onStop: () => void
  onClose: () => void
}

export function LanPanel({ info, devices, busy, error, native, onStart, onStop, onClose }: Props) {
  const { t } = useI18n()
  return (
    <div className="modal" role="dialog" aria-modal="true" aria-label={t('lan.title')} onClick={onClose}>
      <div className="modal__box lan" onClick={(e) => e.stopPropagation()}>
        <h2 className="lan__title">{t('lan.title')}</h2>
        <p className="lan__body">{t('lan.body')}</p>

        {!native && <p className="lan__note">{t('lan.nativeOnly')}</p>}
        {error && <p className="lan__note lan__note--bad">{t('lan.failed', { error })}</p>}

        {info && (
          <>
            {/* generated by the app itself, not user input */}
            <div className="lan__qr" dangerouslySetInnerHTML={{ __html: info.qr }} />
            <a className="lan__url" href={info.url}>
              {info.url}
            </a>
            <p className="lan__scan">{t('lan.scan')}</p>
            <p className="lan__devices">
              <span className="lan__dot" /> {t('lan.hosting')} · {t('lan.connected', { n: devices })}
            </p>
          </>
        )}

        <div className="modal__actions">
          {info ? (
            <button className="btn btn--call" onClick={onStop}>
              {t('lan.stop')}
            </button>
          ) : (
            <button className="btn btn--call" onClick={onStart} disabled={!native || busy}>
              {t('lan.start')}
            </button>
          )}
          <button className="btn btn--ghost" onClick={onClose}>
            {t('about.close')}
          </button>
        </div>
      </div>
    </div>
  )
}
