// Regenerates THIRD-PARTY-NOTICES.md from the actual dependency trees.
//   node scripts/generate-notices.mjs
// Needs `cargo install cargo-license` for the Rust half; without it the Rust
// section is left as-is and a warning is printed.
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'

const root = new URL('..', import.meta.url).pathname
const pkg = JSON.parse(readFileSync(`${root}package.json`, 'utf8'))

const shipped = [
  ['react', 'MIT', 'https://github.com/facebook/react'],
  ['react-dom', 'MIT', 'https://github.com/facebook/react'],
  ['qrcode', 'MIT', 'https://github.com/soldair/node-qrcode'],
  ['dijkstrajs', 'MIT', 'https://github.com/tcort/dijkstrajs'],
  ['pngjs', 'MIT', 'https://github.com/pngjs/pngjs'],
  ['jsQR', 'Apache-2.0', 'https://github.com/cozmo/jsQR'],
]

let rust = []
try {
  const json = execFileSync('cargo', ['license', '--json'], {
    cwd: `${root}src-tauri`,
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
    stdio: ['ignore', 'pipe', 'ignore'],
  })
  rust = JSON.parse(json).filter((c) => c.name !== pkg.name) // not third party: that's us
} catch {
  console.warn('cargo-license not available — skipping the Rust section')
}

const byLicense = new Map()
for (const c of rust) {
  const key = c.license || 'UNKNOWN'
  if (!byLicense.has(key)) byLicense.set(key, [])
  byLicense.get(key).push(`${c.name} ${c.version}`)
}

const out = `# Third-party notices

CrispBingo (\`${pkg.name}\` ${pkg.version}) is distributed under the GNU AGPL v3.0
with an additional permission under section 7 — see [LICENSE](LICENSE). It bundles
the following third-party work.

## Fonts (shipped as .woff2 in the app)

Both are licensed under the **SIL Open Font License, Version 1.1**, reproduced in
full at [licenses/OFL-1.1.txt](licenses/OFL-1.1.txt).

- **Fredoka** — Copyright 2016 The Fredoka Project Authors
  (https://github.com/hafontia/Fredoka-One)
- **Outfit** — Copyright 2021 The Outfit Project Authors
  (https://github.com/Outfitio/Outfit-Fonts)

## Smorfia illustrations

The locally bundled Smorfia SVG illustrations are selected from **Noto Emoji**
(revision 8998f5dd6834), Copyright 2013 Google, Inc., under **Apache-2.0**.
The licence is reproduced at [licenses/Apache-2.0.txt](licenses/Apache-2.0.txt).

## Web frontend (shipped in the bundle)

${shipped.map(([n, l, u]) => `- **${n}** — ${l} — ${u}`).join('\n')}

Build-time only, not shipped: Vite (MIT), TypeScript (Apache-2.0),
@tauri-apps/cli (MIT OR Apache-2.0), gh-pages (MIT).

## Native shell (Tauri, ${rust.length} Rust crates)

The desktop and mobile apps embed a Tauri shell. Tauri itself is dual-licensed
**MIT OR Apache-2.0**. The full crate graph, grouped by licence:

${[...byLicense.entries()]
  .sort((a, b) => b[1].length - a[1].length)
  .map(([lic, crates]) => `### ${lic} (${crates.length})\n\n${crates.sort().join(', ')}`)
  .join('\n\n')}

Nothing in the tree is GPL- or LGPL-only: the ${byLicense.get('MPL-2.0')?.length ?? 0} MPL-2.0 crates are file-level
copyleft and impose no condition that conflicts with app-marketplace
distribution, and every dual-licensed crate is taken under its MIT or Apache-2.0
option.

_Generated by \`scripts/generate-notices.mjs\`._
`

writeFileSync(`${root}THIRD-PARTY-NOTICES.md`, out)
console.log(`THIRD-PARTY-NOTICES.md: ${rust.length} crates, ${byLicense.size} distinct licences`)
