// Writes dist/sw.js with a precache list of everything the build produced, so the
// game runs with no network at all once it has been opened once.
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const dist = new URL('../dist/', import.meta.url).pathname

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry)
    return statSync(full).isDirectory() ? walk(full) : [full]
  })
}

const files = walk(dist)
  .map((f) => relative(dist, f))
  .filter((f) => f !== 'sw.js' && !f.endsWith('.map'))
  .sort()

const version = createHash('sha256')
  .update(files.map((f) => f + readFileSync(join(dist, f)).length).join('|'))
  .digest('hex')
  .slice(0, 12)

const sw = `// generated by scripts/generate-sw.mjs — do not edit
const VERSION = '${version}'
const CACHE_PREFIX = 'crispbingo-'
const CACHE = CACHE_PREFIX + VERSION
const ASSETS = ${JSON.stringify(['./', ...files], null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && (k.startsWith(CACHE_PREFIX) || k.startsWith('bingo-party-'))).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return

  // Pages: prefer the network so a new deploy is picked up, fall back to the cached shell.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match('./index.html').then((r) => r || caches.match('./'))),
    )
    return
  }

  // Hashed assets, fonts, icons: cache first — they never change under the same name.
  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ||
        fetch(request).then((res) => {
          if (res.ok && res.type === 'basic') {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(request, copy))
          }
          return res
        }),
    ),
  )
})
`

writeFileSync(join(dist, 'sw.js'), sw)
console.log(`sw.js: ${files.length + 1} entries precached, version ${version}`)
